Dockerize Prefect Server, Agent and Proxy
DalgoT4D/prefect-proxy pull request #128
Opened 2024-05-29 07:01 UTC by d-jeph

## Feature: Dockerize Prefect Server, Agent and Proxy
### Issue
In the current setup it's not possible to run prefect, prefect agent and the proxy as docker containers. This PR adds the necessary docker files to enable running these services as containers.

### Changes
 Added the following files and folders:
- A `Docker` folder with a `docker_compose.yml` file and `env.template` file. The `docker_compose` file has three services: `prefect_proxy`,`server`, and `agent`
- A `Dockerfile` for the proxy python application
- The `env.template` file contains the necessary environment variables for the `docker_compose` file
- A `docker_compose.dev.yml` for running the services locally during development and testing

2024-05-31 08:20 UTC, Ishankoradia commented
Hi @d-jeph , thank you submitting this PR. Its super helpful. 

For prefect, we have upgraded from `agents` to `workers`.  This [issue](https://github.com/DalgoT4D/platform_infra/issues/35) has the details 
Can we incorporate this in the `docker-compose.yml` ?

Also will we be able to start mutliple workers in the current setup ? On production we use 3 - 2 workers execute work from `ddp` queue and 1 from `manual-dbt` queue.

2024-06-05 07:48 UTC, d-jeph commented
> Hi @d-jeph , thank you submitting this PR. Its super helpful.
> 
> For prefect, we have upgraded from `agents` to `workers`. This [issue](https://github.com/DalgoT4D/platform_infra/issues/35) has the details Can we incorporate this in the `docker-compose.yml` ?
> 
> Also will we be able to start mutliple workers in the current setup ? On production we use 3 - 2 workers execute work from `ddp` queue and 1 from `manual-dbt` queue.

@Ishankoradia Thanks. I will update the code to use workers and also the multiple workers

2024-06-05 11:44 UTC, d-jeph commented
> > Hi @d-jeph , thank you submitting this PR. Its super helpful.
> > For prefect, we have upgraded from `agents` to `workers`. This [issue](https://github.com/DalgoT4D/platform_infra/issues/35) has the details Can we incorporate this in the `docker-compose.yml` ?
> > Also will we be able to start mutliple workers in the current setup ? On production we use 3 - 2 workers execute work from `ddp` queue and 1 from `manual-dbt` queue.
> 
> @Ishankoradia Thanks. I will update the code to use workers and also the multiple workers

@Ishankoradia I have pushed the updated `docker-compose.yml`. I could not find a straight forward way for making the number of workers dynamic so for now I have three different services, one for each worker

2024-06-05 13:37 UTC, d-jeph commented
@fatchat I added a github actions workflow change to this PR as well.

2024-06-06 04:10 UTC, Ishankoradia commented
Thanks @d-jeph i will take a look at this and merge it before the weekend.

2024-06-07 08:01 UTC, Ishankoradia requested changes

2024-06-11 07:25 UTC, d-jeph commented on Docker/docker-compose.dev.yml
> +      - PREFECT_API_DATABASE_CONNECTION_URL=${DB_CONNECTION_URL}
hardcoded the connection url using the db service credentials

2024-06-11 07:25 UTC, d-jeph commented on Docker/docker-compose.yml
> +      - prefect_postgres_db
Thanks - I made the correct

2024-06-11 07:26 UTC, d-jeph commented on Docker/docker-compose.dev.yml
> +      PGDATA: /data/postgres
Postgres should now automatically create the db using the value provided in the `POSTGRES_DB` var

2024-06-21 12:38 UTC, Ishankoradia commented
Hi @d-jeph , the docker compose works very nicely. I am able to run proxy + prefect on my current local database via docker.

One thing i noticed, when i run an existing prefect deployment (from its UI, where prefect is running via docker). It throws this error. Although the flow is getting submitted to the container worker but looks like it is still trying to find the code (to be run) from the host. 
Wanted to check if you have faced this before, looks we might have to update the existing deployment to read from prefect-proxy's storage instead of host somehow.

<img width="1057" alt="Screenshot 2024-06-21 at 18 05 17" src="https://github.com/DalgoT4D/prefect-proxy/assets/39583356/ff1c2da9-6b9b-4e54-8470-de707cb9b2f3">

2024-06-24 12:37 UTC, d-jeph commented
@Ishankoradia Thanks for flagging this. 
Yes we experienced the same issue when we tested this on GCP. 
I have updated the docker compose files to add a shared volume between the proxy service(where the flow code lives) and the prefect worker containers. This should help prefect get access to the flow code. Please test and let me know if you get any errors.

2024-06-25 15:22 UTC, Ishankoradia commented
Hey @d-jeph thanks for making the changes. This is what i found in testing experiment
- I ran `docker compose up` on my local prefect that has whole lot of deployments setup
- I tried running one of them , it gave the same error as above. To make it work i had to go into prefect's database, navigate to table `depolyment` and update the column `path` to `/app`.  This is absolutely fine, we could run a script that does this for our current deployments if/when we move to dockerize production deployment.
- After making the above change, i again ran the same deployment & this time i got the below error. (Looks like its finding the code now)
<img width="1198" alt="Screenshot 2024-06-25 at 20 51 46" src="https://github.com/DalgoT4D/prefect-proxy/assets/39583356/e7fcfe40-296c-467f-a477-05ffaf5328c9">

2024-06-26 15:43 UTC, d-jeph commented
@Ishankoradia Thanks for sharing this. 
I have now setup a new Docker file `Dockerfile.prefect_server` that creates a prefect server image that includes the same dependencies as the proxy service - this is the image used now in the docker compose for the prefect server and worker service. When I used the proxy `requirements.txt` I however got an error `cannot import name 'safe _get_annotation' from 'griffe.agents-nodes'` so I had to upgrade the `griffe` package to the newest version `0.47.0`. Please let me know if you've encountered the error

I have also noticed the team upgraded prefect to a new version `2.18.3` so I upgraded the image used as well.

Please test and let me know if you experience any errors on your end.

2024-07-31 06:23 UTC, Ishankoradia commented
Hi @d-jeph , i have tested it out. Thanks for making the changes and ugprading the images with the newer prefect version.

Just want to reconfirm that this is still true ? (second point from my last comment)
```
I tried running one of them , it gave the same error as above. To make it work i had to go into prefect's database, navigate to table depolyment and update the column path to /app. This is absolutely fine, we could run a script that does this for our current deployments if/when we move to dockerize production deployment.
```

After doing the above, it is able to download the code & submit flow but I get this error then
```
Worker 'prefect-worker-ddp-2' submitting flow run '8379079c-b9e5-4e8c-8fbe-636f60ff77a7'
11:49:31 AM
prefect.flow_runs.worker
Opening process...
11:49:31 AM
prefect.flow_runs.worker
Completed submission of flow run '8379079c-b9e5-4e8c-8fbe-636f60ff77a7'
11:49:31 AM
prefect.flow_runs.worker
Downloading flow code from storage at '/app'
11:49:32 AM
prefect.flow_runs
Created subflow run 'nickel-snake' for flow 'run-airbyte-connection-flow-v1'
11:49:33 AM
prefect.flow_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmpru5nmvdsprefect/proxy/prefect_flows.py", line 246, in deployment_schedule_flow_v4
    run_airbyte_connection_flow_v1(task_config)
  File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 1246, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 293, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 752, in create_and_begin_subflow_run
    return await terminal_state.result(fetch=True)
  File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmpru5nmvdsprefect/proxy/prefect_flows.py", line 48, in run_airbyte_connection_flow_v1
    result = run_connection_sync(connection_block)
  File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 1246, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 293, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 752, in create_and_begin_subflow_run
    return await terminal_state.result(fetch=True)
  File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/usr/local/lib/python3.10/site-packages/prefect_airbyte/flows.py", line 57, in run_connection_sync
    airbyte_sync = await task(airbyte_connection.trigger.aio)(airbyte_connection)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(tim [...]

2024-09-02 07:01 UTC, Ishankoradia commented
Hi @d-jeph , sorry getting back late on this.
I tried with the remote RDS with no firewall like we discussed. But i am gettting the same error

Its able to fetch the code and submit for flow run but then it loses connection. 

Also i had to comment these lines for it to connect to the remote RDS (in `docker-compose.yml`)
```
volumes:
  prefect:
  postgres:
  flows_volume:
# networks:
#   default:
#     name: prefect-network
```




> Hi @d-jeph , i have tested it out. Thanks for making the changes and ugprading the images with the newer prefect version.
> 
> Just want to reconfirm that this is still true ? (second point from my last comment)
> 
> ```
> I tried running one of them , it gave the same error as above. To make it work i had to go into prefect's database, navigate to table depolyment and update the column path to /app. This is absolutely fine, we could run a script that does this for our current deployments if/when we move to dockerize production deployment.
> ```
> 
> After doing the above, it is able to download the code & submit flow but I get this error then
> 
> ```
> Worker 'prefect-worker-ddp-2' submitting flow run '8379079c-b9e5-4e8c-8fbe-636f60ff77a7'
> 11:49:31 AM
> prefect.flow_runs.worker
> Opening process...
> 11:49:31 AM
> prefect.flow_runs.worker
> Completed submission of flow run '8379079c-b9e5-4e8c-8fbe-636f60ff77a7'
> 11:49:31 AM
> prefect.flow_runs.worker
> Downloading flow code from storage at '/app'
> 11:49:32 AM
> prefect.flow_runs
> Created subflow run 'nickel-snake' for flow 'run-airbyte-connection-flow-v1'
> 11:49:33 AM
> prefect.flow_runs
> Encountered exception during execution:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
>     raise exc from None
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
>     response = await connection.handle_async_request(
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
>     stream = await self._connect(request)
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
>     stream = await self._network_backend.connect_tcp(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
>     return await self._backend.connect_tcp(
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
>     with map_exceptions(exc_map):
>   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ConnectError: All connection attempts failed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
>     result = await flow_call.aresult()
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
>     return await asyncio.wrap_future(self.future)
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
>     result = self.fn(*self.args, **self.kwargs)
>   File "/tmp/tmpru5nmvdsprefect/proxy/prefect_flows.py", line 246, in deployment_schedule_flow_v4
>     run_airbyte_connection_flow_v1(task_config)
>   File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 1246, in __call__
>     return enter_flow_run_engine_from_flow_call(
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 293, in enter_flow_run_engine_from_flow_call
>     retval = from_sync.wait_for_call_in_loop_thread(
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
>     return call.result()
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
>     return self.future.result(timeout=timeout)
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
>     result = await coro
>   File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
>     return await fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 752, in create_and_begin_subflow_run
>     return await terminal_state.result(fetch=True)
>   File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
>     raise await get_state_exception(state)
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
>     result = await flow_call.aresult()
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
>     return await asyncio.wrap_future(self.future)
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
>     result = self.fn(*self.args, **self.kwargs)
>   File "/tmp/tmpru5nmvdsprefect/proxy/prefect_flows.py", line 48, in run_airbyte_connection_flow_v1
>     result = run_connection_sync(connection_block)
>   File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 1246, in __call__
>     return enter_flow_run_engine_from_flow_call(
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 293, in enter_flow_run_engine_from_flow_call
>     retval = from_sync.wait_for_call_in_loop_thread(
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
>     return call.result()
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
>     return self.future.result(timeout=timeout)
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
>     result = await coro
>   File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
>     return await fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 752, in create_and_begin_subflow_run
>     return await terminal_state.result(fetch=True)
>   File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
>     raise await get_state_exception(state)
>   File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
>     result = await flow_call.aresult()
>   File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
>      [...]

2024-11-07 06:26 UTC, fatchat approved these changes

2024-11-08 04:00 UTC, Ishankoradia approved these changes

2024-11-08 04:02 UTC, merged